services:
  - type: web
    name: medvault-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --legacy-peer-deps
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: medvault-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 15m
      - key: REFRESH_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://medvault-frontend.onrender.com

  - type: web
    name: medvault-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://medvault-backend.onrender.com/api

databases:
  - name: medvault-db
    databaseName: medvault
    user: medvault_user
    plan: free